# -*- coding: utf-8 -*-
"""adjective_draft

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MIt2fbsY1NDudkF2oISA02zsQHQwu8sU

# Authorship Analysis

## 参考サイト

pos_tag list
https://qiita.com/syunyo/items/2c1ce1d765f46a5c1d72

python class
https://snowtree-injune.com/2019/02/11/python-class-necessity/

nltk
https://www.nltk.org/

## Download
"""

!pip install nltk

import nltk

# 必要なパッケージ、データ、ドキュメントのダウンロード (時間がかかる)
nltk.download('all')

"""## import"""

from nltk import pos_tag
from nltk import word_tokenize

"""## Code"""

class AA_adjectives :
  def __init__(self) :
    self.words_all = [] # 全ての単語
    self.words_adjectives = [] # 形容詞のみ
    self.AdjectivesTagsName = ['JJ', 'JJR', 'JJS'] # 形容詞のタグ

  def get_adjectives(self) :
    self.words_all = pos_tag(self.words_all)

    for i,j in self.words_all :
      adj = False
      for k in self.AdjectivesTagsName :
        if j == k :
          adj = True
          break

      if adj :
        self.words_adjectives.append({i:j})

def main() :

  sentence1 = """At eight o'clock on Thursday morning Arthur didn't feel most slowly."""

  test1 = AA_adjectives()
  test1.words_all = word_tokenize(sentence1)

  print(test1.words_all)
  test1.get_adjectives()
  print(test1.words_all)
  print(test1.words_adjectives)

def test() :
  words = ['useful']

  tags = pos_tag(words)

  print(tags)

if __name__ == '__main__' :
  main()